# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
short_commit_hash = sh("git rev-parse --short HEAD").strip

platform :ios do
  desc 'Description of what the lane does'
  lane :custom_lane do

    UI.message 'Building IPA to /output folder...'

    puts("moises")
    # # match(type:'adhoc')

    # UI.message 'before gym'

    # gym(
    #   scheme: 'BullsEye',
    #   export_method: 'ad-hoc',
    #   configuration: 'Debug',
    #   silent: true,
    #   suppress_xcode_output: false,
    #   include_symbols: true,
    #   include_bitcode: true,
    #   export_options: {
    #     uploadBitcode: false,
    #     uploadSymbols: false,
    #     compileBitcode: false,
    #   }
    # )

    # UI.message 'after gym'

    # UI.message 'Uploading IPA to Nightly Build on App Center...'
    # release_notes = '1231 12 uploaded via fastlane nightly_build '

    # testfairy(
    #   upload_url: 'https://app.testfairy.com',
    #   comment: release_notes,
    #   auto_update: 'on'
    # )

    # build_type = (ENV['BUILD_TYPE']  unless ENV['BUILD_TYPE'].to_s.empty?) || "1231231"

    # puts "variable : " + build_type

  end

    desc 'Lane added tags a commit'
    lane :build_qa do 
      add_git_tag(
        tag: "publisher-qa-" + short_commit_hash
      )
    end 

end
