name: ios-beta-build
on:
  workflow_dispatch:
  push:
    branches:
      - "beta"
jobs:
  build-macos:
    runs-on: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "WW-Digital/kurbo-ios"
          ref: develop
          ssh-key: ${{ secrets.ssh_ww }}
      
      - name : Beta build
        run: |
          bundle install
          bundle exec fastlane beta
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FIREBASEAPPDISTRO_APP: "1:304579675699:ios:8665fc7079fd3e34d24546"
          FIREBASEAPPDISTRO_IPA_PATH: "output/gym/Kurbo Dev.ipa"
          FIREBASEAPPDISTRO_GROUPS: "development"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "scan"
          path: output/scan/**/*
