name: 'Test'

on:
  workflow_dispatch:

jobs:
  prueba-envs:
    runs-on: macos
    steps:
      - name: Checout
        uses: actions/checkout@v2.4.0
      - name: test
        run: |
          echo "$GITHUB_ENV"
          echo "${{ env.SLACK_USER_ID }}"
