name: 'Test'

on:
  workflow_dispatch:

jobs:
  prueba-envs:
    runs-on: macos
    steps:
      - uses: ./.github/workflows/device
      - name: Checout
        uses: actions/checkout@v2.4.0
      - name: test
        run: |
          echo "$GITHUB_ENV"
          echo $GITHUB_ENV.SLACK_USER_ID
          echo $SLACK_USER_ID
          echo "${{ env.SLACK_USER_ID }}"
