name: 'Test'

on:
  workflow_dispatch:

# jobs:
#   prueba-envs:
#     runs-on: macos
#     steps:
#       - name: envs
#         run: echo "SLACK_USER_ID=${{ github.event.inputs.slack_user_id }}" >> $GITHUB_ENV
        
#       - name: Checout
#         uses: actions/checkout@v2.4.0
#       - uses: ./.github/workflows/device.yml
#       - name: test
#         run: |
#           echo "$GITHUB_ENV"
#           echo $GITHUB_ENV.SLACK_USER_ID
#           echo $SLACK_USER_ID
#           echo "${{ env.SLACK_USER_ID }}"
  
