# name: ios-dev-build
# on:
#   push:
#     branches:
#       - "develop"
# jobs:
#   build-macos:
#     runs-on: macos
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           repository: "WW-Digital/kurbo-ios"
#           ref: develop
#           ssh-key: ${{ secrets.ssh_ww }}
      
#       - name : Dev build
#         run: |
#           bundle install
#           bundle exec fastlane dev 
      
#       - name: Upload a Build Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: "scan"
#           path: output/scan/**/*