name: Device

on:
  workflow_dispatch:
    inputs:
      pruebas:
        description: 'random input'
        type: string
        required: true
  
jobs:
 super:
  runs-on: self-hosted
  steps:
    - name: Checout
      uses: actions/checkout@v2.4.0
      
    - name: Execute fastlane command
      run: echo $PRUEBA
      env: 
        PRUEBA: ${{ github.event.inputs.pruebas }}
   
    - name: test conditional
      if: ${{ env.PRUEBA == 'hello' }}
      run: echo 'pass condition'
        
