name: Fastlane passthrough

on:
  workflow_dispatch:

jobs:
 super:
  runs-on: macos
  steps:
    - name: Checout
      uses: actions/checkout@v2.4.0

    - name: Execute fastlane command
      run: echo 'hello from github'
      env:
        RUN_STEP: ${{ github.actions.RUN_STEP }}
