name: Device

on:
  workflow_dispatch:
    inputs:
      slack_user_id:
        description: 'random input 1'
        type: string
        required: true
      fastlane_name:
        description: 'random input 2'
        type: string
        required: true
      device_name:
        description: 'random input 3'
        type: string
        required: true
      device_udid:
        description: 'random input 4'
        type: string
        required: true
        
  
jobs:
 super:
  runs-on: self-hosted
  steps:
    - name: Checout
      uses: actions/checkout@v2.4.0
      
    - name: Execute fastlane command
      run: echo ${{ github.event.inputs.device_udid }} >> $GITHUB_ENV
      env: 
        PRUEBA: ${{ env.device_udid }}
        
