name: Fastlane passthrough

on:
  workflow_dispatch:
    inputs:
      pruebas:
        type: string
        required: true
  
jobs:
 super:
  runs-on: self-hosted
  steps:
    - name: Checout
      uses: actions/checkout@v2.4.0
      
    - name: Execute fastlane command
      env: 
        PRUEBA: ${{ github.event.inputs.prueba }}
      run: echo $PRUEBA
        
