name: Device

on:
  workflow_dispatch:
    inputs:
      slack_user_id:
        description: 'random input 1'
        type: string
        required: true
      fastlane_name:
        description: 'random input 2'
        type: string
        required: true
      device_name:
        description: 'random input 3'
        type: string
        required: true
      device_udid:
        description: 'random input 4'
        type: string
        required: true
        
  
jobs:
 super:
  runs-on: macos
  steps:
    - name: Execute fastlane command
      run: |
        echo "SLACK_USER_ID=${{ github.event.inputs.slack_user_id }}" >> $GITHUB_ENV
        echo "FASTLANE_NAME=${{ github.event.inputs.fastlane_name }}" >> $GITHUB_ENV
        echo "DEVICE_NAME=${{ github.event.inputs.device_name }}" >> $GITHUB_ENV
        echo "DEVICE_UDID=${{ github.event.inputs.device_udid }}" >> $GITHUB_ENV
    - name: secod env
      run: echo "${{ env.SLACK_USER_ID }}"
      env: 
        SLACK_USER_ID: ${{ env.SLACK_USER_ID }}
      
 super-tow:
  runs-on: macos
  steps:     
    - name: three env
      run: |
        echo $SLACK_USER_ID
        echo "${{ env.SLACK_USER_ID }}"
