name: ios-beta-build
on:
  push:
    branches:
      - "beta"
jobs:
  build-macos:
    runs-on: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "WW-Digital/kurbo-ios"
          ref: develop
          ssh-key: ${{ secrets.ssh_ww }}
      
      - name : Beta build
        run: |
          bundle install
          bundle exec fastlane beta
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "scan"
          path: output/scan/**/*