name: labels-events

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_disapatch:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - name: Test01
      if: github.event.label.name == 'label-test'
      run: |
        echo "hello from first step"
        echo ${{ github.workflow }}
        echo ${{ github.ref }}
    - name: Test01.1
      run: echo "hello from the first step 01"
  
  test2:
    runs-on: ubuntu-latest
    steps:
    - name: Test02
      if: github.event.label.name == 'label-test1'
      run: |
        echo "hello from second step"
        echo "hello 2 from second step"

  test3:
    runs-on: macos-lastest
    steps:
    - name: TesT03
      run: |
        echo ${{ github.workflow }}
    