name: labels-events

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:
  test1:
  runs-on: ubuntu-latest
  steps:
    - name: Test01
      run: echo "hello from first step"
  
  test2:
  runs-on: ubuntu-latest
  steps:
    - name: Test02
      run: echo "hello from second step"