name: labels-events

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on: 
  pull_request:
    types: [ labeled, synchronize ]
  workflow_dispatch:
    inputs:
      user_email:
         description: "App name"
         type: string
         required: true
      user_group:
         description: "Group Name"
         type: string
         required: false

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    
    - name: Test0
      run: |
        

    - name: Test01
      if: github.event.label.name == 'label-test'
      run: |
        echo "hello from first step"
        echo ${{ github.workflow }}
        echo ${{ github.ref }}

    - name: Test01.1
      run: echo "hello from the first step 01"
  
  test2:
    runs-on: ubuntu-latest
    steps:
    - name: Test02
      if: github.event.label.name == 'label-test1'
      run: |
        echo "hello from second step"
        echo "hello 2 from second step"

  test3:
    runs-on: macos-11
    steps:
    - name: TesT03
      if: github.event.label.name == 'label-test2'
      run: |
        echo "inside"
        echo ${{ github.workflow }}
    
