name: labels-events

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  pull_request:
    types: [ labeled, synchronize ]
  # workflow_dispatch:
  #   inputs:
  #     user_email:
  #        description: "App name"
  #        type: string
  #        required: true
  #     user_group:
  #        description: "Group Name"
  #        type: string
  #        required: false

jobs:
  test-01:
    runs-on: self-hosted
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        touch github.json
        echo "$GITHUB_CONTEXT" > github.json
        
    - name: Testing labels evetn 0
      if: contains(github.event.pull_request.labels.*.name, 'label-test')
      run: echo "${{ github.event.pull_request.labels.*.name }}"

    # call-workflow-test:
    #   if: github.event.label.name == 'label-test'  
    #   uses: ./.github/workflows/nightly-test.yml   
      
#           uses: ./.github/workflows/nightly-test.yml
        
#       - name: Git clone
#         uses: actions/checkout@v3
#         with:
#           repository: rewardStyle/mobile-ios
#           ssh-key: ${{ secrets.SSH_LTK }}
          
#       - name: Git Pull LFS
#         run: |
#          git lfs pull -I '/Apps/Consumer/Shoproll/**'

  #   - name: Test01
  #     if: github.event.label.name == 'label-test'
  #     run: |
  #       echo "hello from first step"
  #       echo ${{ github.workflow }}
  #       echo ${{ github.ref }}

  #   - name: Test01.1
  #     run: echo "hello from the first step 01"
  
  test2:
    runs-on: ubuntu-latest
    steps:
    - name: testing label 2
      if: contains(github.event.pull_request.labels.*.name, 'label-test')
      run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"

  test3:
    runs-on: macos-11
    steps:
    - name: testing label 3
      if: contains(github.event.pull_request.labels.*.name, 'label-test2')
      run: echo "hello from last label"
    
