name: labels-events

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  pull_request:
    types: [ labeled, synchronize ]
  # workflow_dispatch:
  #   inputs:
  #     user_email:
  #        description: "App name"
  #        type: string
  #        required: true
  #     user_group:
  #        description: "Group Name"
  #        type: string
  #        required: false

jobs:
#   test-label-01:
#     name: test-label-01
#     if: ${{ (contains(github.event.pull_request.labels.*.name, 'label-test') && github.event.action == 'labeled') || (contains(github.event.pull_request.labels.*.name, 'label-test') && github.event.action == 'synchronize') }}
#     uses: ./.github/workflows/build-and-test.yml
#     with:
#       working_directory: 'Apps/Consumer/Shoproll'
#     secrets:
#       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  test-label-02:
    name: ${{ github.event.label.name }}
    if: ${{ contains(fromJSON('["label-test1", "label-test"]'), github.event.label.name) }}
    runs-on: macos-12
    steps:
        - name: ${{ github.event.label.name }}
          run: |
            echo ${{ github.event.pull_request.labels.*.name }}
            echo ${{ ${{ github.event.label.name }} }}
#       - name: Git clone
#         uses: actions/checkout@v3
#         with:
#           repository: rewardStyle/mobile-ios
#           ssh-key: ${{ secrets.SSH_LTK }}
          
#       - name: Set Xcode Version
#         run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
        
#       - name: Update fastlane
#         working-directory: 'Apps/Consumer/Shoproll'
#         run: bundle update fastlane
        
#       - name: Install Ruby dependencies
#         working-directory: 'Apps/Consumer/Shoproll'
#         run: bundle install
        
#       - name: Run Unit Tests
#         working-directory: 'Apps/Consumer/Shoproll'
#         run: |
#           bundle exec fastlane run_unit_test
#           mkdir -p output/scan
#           touch output/scan/report.html
#           touch output/scan/report.junit
          
  
#   test-label-03:
#     name: test-label-03
#     if: contains(github.event.pull_request.labels.*.name, 'label-test2')
#     uses: ./.github/workflows/build-and-test.yml
#     with:
#       working_directory: 'Apps/Publisher/rewardStyle'
#     secrets:
#       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: |
    #     touch github.json
    #     echo "$GITHUB_CONTEXT" > github.json
        
    # - name: Testing labels evetn 0
      
    #   run: echo "${{ github.event.pull_request.labels.*.name }}"

    # call-workflow-test:
    #   if: github.event.label.name == 'label-test'  
    #   uses: ./.github/workflows/nightly-test.yml   
      
#           uses: ./.github/workflows/nightly-test.yml
        
#       - name: Git clone
#         uses: actions/checkout@v3
#         with:
#           repository: rewardStyle/mobile-ios
#           ssh-key: ${{ secrets.SSH_LTK }}
          
#       - name: Git Pull LFS
#         run: |
#          git lfs pull -I '/Apps/Consumer/Shoproll/**'

  #   - name: Test01
  #     if: github.event.label.name == 'label-test'
  #     run: |
  #       echo "hello from first step"
  #       echo ${{ github.workflow }}
  #       echo ${{ github.ref }}

  #   - name: Test01.1
  #     run: echo "hello from the first step 01"
  
  # test2:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: testing label 2
  #     if: contains(github.event.pull_request.labels.*.name, 'label-test')
  #     run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"

  # test3:
  #   runs-on: macos-11
  #   steps:
  #   - name: testing label 3
  #     if: contains(github.event.pull_request.labels.*.name, 'label-test2')
  #     run: echo "hello from last label"
    
