name: WW-Layout

on: 
 workflow_dispatch:
jobs:
  unit-test-4:
    runs-on: macos-11
    env:
     DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
    steps:
#       - name: checkout
#         uses: actions/checkout@v2  
#         # with: 
        #   repository: "ww-tech/wwlayout"
        #   ref: develop
        #   ssh-key: ${{ secrets.ssh_ww }}
      - name: Xcode version
        run: |
         xcodebuild -version
         
         
         
#       - name: Install dependencies in Gemfile
#         run: bundle install
     
#       - name:  Unit Tests, using Swift 4.0
#         run: |
#           bundle exec fastlane scan \
#                         --device "iPhone SE" \
#                         --xcargs "SWIFT_VERSION=4.0" \
#                         --code_coverage \
#                         --output_directory output/scan 
      
#       - name:  Unit Tests, using Swift 4.2
#         run: |
#           bundle exec fastlane scan \
#                         --device "iPhone 8" \
#                         --xcargs "SWIFT_VERSION=4.2" \
#                         --code_coverage \
#                         --output_directory output/scan
            
#       - name:  Unit Tests, using Swift 5.0
#         run: |
#           bundle exec fastlane scan \
#                         --device "iPhone X" \
#                         --xcargs "SWIFT_VERSION=5.0" \
#                         --code_coverage \
#                         --output_directory output/scan
      
#       - name:  Unit Tests, using Swift 5.1
#         run: |
#           bundle exec fastlane scan \
#                         --device ["iPhone 6", "iPhone 11"] \
#                         --xcargs "SWIFT_VERSION=5.1" \
#                         --code_coverage \
#                         --output_directory output/scan
            
#       - name:  Unit Tests, using Swift 5.2
#         run: |
#           bundle exec fastlane scan \
#                        --device ["iPhone 7", "iPhone XS"] \
#                        --xcargs "SWIFT_VERSION=5.2" \
#                        --code_coverage \
#                        --output_directory output/scan 
            
#       - name:  Unit Tests, using Swift 5.3
#         run: |
#           bundle exec fastlane scan \
#                         --device ["iPhone 8", "iPhone SE"] \
#                         --xcargs "SWIFT_VERSION=5.3" \
#                         --code_coverage \
#                         --output_directory output/scan
            
#       - name:  Build example (test spm)
#         run: |
#            xcodebuild build \
#               -project "WWLayoutExample/WWLayoutTV/WWLayoutTV.xcodeproj" \
#               -scheme "WWLayoutTV" \
#               -destination "platform=tvOS Simulator,name=Apple TV"
  test-self-hosted:
     runs-on: macos
     env:
       DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
     steps: 
      - name: Another version
        run: |
         xcodebuild -version 
