name: LTK-child-2

on:
  workflow_dispatch:
  
# env:
# #   PRUEBAS:environment: pruebas
  

# jobs:
#   call-workflow-test:
#     uses: ./.github/workflows/LTK-principal.yml
#     with:
#       nombre: "Moises"
#     secrets:
#       PRUEBAS:environment: pruebas
    
    
    
      
