name: LTK-child-2

on:
  workflow_dispatch:

jobs:
  call-workflow-test:
    uses: ./.github/workflows/LTK-principal.yml
    with:
      nombre: "Moises"
    secrets:
      PRUEBAS: "Valordesdeelotroyml"
    
    
    
      
