name: TestFairy

on:
  workflow_dispatch:

jobs:
  testfairy-upload:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Dev build
        run: |
          bundle install
          bundle exec pod update
          touch .bash_env
          export BASH_ENV="$GITHUB_WORKSPACE/.bash_env"
      
      - name: Updload IPA to TestFairy
        run: |
          source "$GITHUB_WORKSPACE/.bash_env"
          bundle exec fastlane custom_lane
        env:
          TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: gym
          path: output/**/*

      - name: Post job cleanup
        run: git clean -ffdxq
        if: always()
        continue-on-error: true
