name: TestFairy-0.1

on:
  workflow_dispatch:
#     inputs:
#       build_type:
#         description: "adasada"
#         type: string

jobs:
  testfairy-upload:
    runs-on: self-hosted
    steps:
      # - name: checkout
      #   uses: actions/checkout@v2
      - name: Dev build
        run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          echo "${{ secrets.SSH_LTK }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          git clone https://github.com/rewardStyle/mobile-ios.git
          
      - name: Git Pull LFS
        run:  git lfs pull -I 'mobile-ios'
        # env: 
        #  BUILD_TYPE: ${{ github.event.inputs.build_type }}
          
      # - name: Updload IPA to TestFairy
      #   run: |
      #     bundle exec fastlane custom_lane
      #   env:
      #     FL_TESTFAIRY_API_KEY: ${{ secrets.TESTFAIRY_API_KEY }}
      
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: gym
      #     path: output/**/*

      # - name: Post job cleanup
      #   run: git clean -ffdxq
      #   if: always()
      #   continue-on-error: true
