name: file-tes
on: 
  workflow_dispatch:
   inputs:
      simulator:
        description: Create a build and run ui test in simulator
        type: boolean
        required: false
        default: "true"

jobs:
  unit-test:
    if: github.event.inputs.simulator == 'true'
    runs-on: macos
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: echo 'from input1'
