name: Fastlane passthrough

on:
  workflow_dispatch:
    inputs:
      fastlane_name:
        description: "Name of lane to run"
        type: string
        required: true
      env:
        description: "Environment variables required to run the lane"
        type: string
        required: false

jobs:
  fastlane-passthrough:
    runs-on: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set environment variables
        if: ${{ github.event.inputs.env }}
        run: echo '${{ github.event.inputs.env }}' | jq -r 'paths(scalars) as $p | "\($p|join("_"))=\(getpath($p))"' >> $GITHUB_ENV
      
#       - name: Set secrets for register_development_device register_adhoc_device
#         if: contains(github.event.inputs.fastlane-name, 'register_')
#         run: |
#           echo 'APPSTORECONNECTAPI_KEYID=${{ secrets.APPSTORECONNECTAPI_KEYID }}
#           APPSTORECONNECTAPI_ISSUERID=${{ secrets.APPSTORECONNECTAPI_ISSUERID }}
#           APPSTORECONNECTAPI_KEYCONTENTS=${{ secrets.APPSTORECONNECTAPI_KEYCONTENTS }}
#           MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}
#           FASTLANE_SESSION=${{ secrets.FASTLANE_SESSION }}' >> $GITHUB_ENV
#       - name: Run lane
#         run: |
#           # source "$GITHUB_WORKSPACE/.bash_env"
#           bundle exec fastlane ${{ github.event.inputs.fastlane-name }}
